### ISSUE TITLE
Some questions about PyTorch plugin in PLUMED

### ISSUE THREAD

**Issue by yanze039** [zwpku/torchann-plumed#1]
Hi Wei,
A very nice work about neural CV in this repo! Thanks for you to make it open source. 
Currently, I am doing something similar but using NN as free energy representation and then biasing simulation by NNs. Do you have some instructions about how to compile new plumed modules (like, how to register keys or so)? I would really appreciate it if you can share them with me!
Since I couldn't find your email anywhere, I opened this issues. (just feel free to close it). I would also be glad more if you can share  your email with me.

**Comment by zwpku** [comment]
1) There are some instructions on the PLUMED website:
https://www.plumed.org/doc-master/developer-doc/html/pages.html
For example,  the page below explains how to add a new function to PLUMED:
https://www.plumed.org/doc-master/developer-doc/html/_adding_a_function.html
2) One can also figure out how to add new modules by reading the existing ones in the source code of PLUMED. 
Hopefully they will be helpful!
